name: YOLO
server:
  cut-layer: a #or b, c
  clients:
    - 1
    - 1
  model: yolov8n
  batch-frame: 1
rabbit:
  address: 127.0.0.1
  username: guest
  password: guest
  virtual-host: /

data: video.mp4
log-path: .
control-count: 10
debug-mode: False
